/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ng-bootstrap-form-validation.module';
import * as import2 from '@angular/common';
import * as import3 from './Services/error-message.service';
import * as import4 from './Tokens/tokens';
class NgBootstrapFormValidationModuleRootInjector extends import0.ɵNgModuleInjector<import1.NgBootstrapFormValidationModuleRoot> {
  _CommonModule_0:import2.CommonModule;
  _NgBootstrapFormValidationModuleRoot_1:import1.NgBootstrapFormValidationModuleRoot;
  __NgLocalization_2:import2.NgLocaleLocalization;
  __ErrorMessageService_3:import3.ErrorMessageService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  get _ErrorMessageService_3():import3.ErrorMessageService {
    if ((this.__ErrorMessageService_3 == null)) { (this.__ErrorMessageService_3 = new import3.ErrorMessageService(this.parent.get(import4.CUSTOM_ERROR_MESSAGES))); }
    return this.__ErrorMessageService_3;
  }
  createInternal():import1.NgBootstrapFormValidationModuleRoot {
    this._CommonModule_0 = new import2.CommonModule();
    this._NgBootstrapFormValidationModuleRoot_1 = new import1.NgBootstrapFormValidationModuleRoot();
    return this._NgBootstrapFormValidationModuleRoot_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.NgBootstrapFormValidationModuleRoot)) { return this._NgBootstrapFormValidationModuleRoot_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    if ((token === import3.ErrorMessageService)) { return this._ErrorMessageService_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const NgBootstrapFormValidationModuleRootNgFactory:import0.NgModuleFactory<import1.NgBootstrapFormValidationModuleRoot> = new import0.NgModuleFactory<any>(NgBootstrapFormValidationModuleRootInjector,import1.NgBootstrapFormValidationModuleRoot);
class NgBootstrapFormValidationModuleInjector extends import0.ɵNgModuleInjector<import1.NgBootstrapFormValidationModule> {
  _NgBootstrapFormValidationModule_0:import1.NgBootstrapFormValidationModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.NgBootstrapFormValidationModule {
    this._NgBootstrapFormValidationModule_0 = new import1.NgBootstrapFormValidationModule();
    return this._NgBootstrapFormValidationModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.NgBootstrapFormValidationModule)) { return this._NgBootstrapFormValidationModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const NgBootstrapFormValidationModuleNgFactory:import0.NgModuleFactory<import1.NgBootstrapFormValidationModule> = new import0.NgModuleFactory<any>(NgBootstrapFormValidationModuleInjector,import1.NgBootstrapFormValidationModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovYml0YnVja2V0L3BlcnNvbmFsL2FuZ3VsYXItYm9vdHN0cmFwLWZvcm0tdmFsaWRhdGlvbi9saWIvbmctYm9vdHN0cmFwLWZvcm0tdmFsaWRhdGlvbi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovYml0YnVja2V0L3BlcnNvbmFsL2FuZ3VsYXItYm9vdHN0cmFwLWZvcm0tdmFsaWRhdGlvbi9saWIvbmctYm9vdHN0cmFwLWZvcm0tdmFsaWRhdGlvbi5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
